### ISSUE TITLE
Issue with Angular 1.3.0-beta.18

### ISSUE THREAD

**Issue by russellf9** [itslenny/angular-pretty-checkable#4]
When using a `pretty-checkbox` with the latest version of the Angular ( 1.3.0-beta.18 ) the ng-model value becomes `undefined` resulting in an error.

To replicate - simply check, uncheck and check again

( I'll set up a fiddle.js to see if I can replicate this issue for you to see. )

**Comment by itslenny** [comment]
Yea, I think that was a mistake. It was fixed as part of this [pull request](https://github.com/itslenny/angular-pretty-checkable/commit/27366d904f827957a9ba66f426637f1809823969)
