### ISSUE TITLE
Update module to provide better support for disabled

### ISSUE THREAD

**Issue by Josh68** [itslenny/angular-pretty-checkable#7]
Not sure if this is unique to my environment, but I can't get dynamic disabling/enabling of the components to work. ~~but the only way I could get updating the disabled attribute to work on your checkboxes was to use the following undocumented Angular syntax in my markup:~~

~~data-attr-disabled="{{model.value}}"~~

~~No luck at all using plain "disabled" or "ng-disabled."~~ In all cases, the input itself updated correctly, but the anchor tag retained the disabled class because it wasn't correctly evaluating the attribute value on model updates.

In your source, I might propose something like this. Here's line 111:

```
element.find("a").toggleClass(buttonsCtrl.disabledClass, (attrs.disabled || attrs.ngDisabled) ? true : false);
```

Would it be ok to add scope.$eval() options in the ternary statement?

```
element.find("a").toggleClass(buttonsCtrl.disabledClass, (attrs.disabled || attrs.ngDisabled || scope.$eval(attrs.disabled) || scope.$eval(attrs.ngDisabled)) ? true : false);
```

I need to play around with the module more to see how radio buttons go.

Thanks for your module, since it's really the only OOB solution I've gotten working in my project.

**Comment by Josh68** [comment]
Actually, now I realize the only thing that works for me is to change your code to:

```
element.find("a").toggleClass(buttonsCtrl.disabledClass, (scope.$eval(attrs.disabled) || scope.$eval(attrs.ngDisabled)) ? true : false);
```

Otherwise, I think more logic would need to be added to see if the unevaluated model strings (in the simple example, 'true' or 'false') work correctly in the ternary operation. Any other kind of string, like "model.value' will not work correctly unless it can be successfully evaluated as truthy or falsy.

**Comment by itslenny** [comment]
Got this fixed in the latest version. Your fix was close, but didn't work well with ng-disabled. I made it work similar to ng-required with an $observe on the attribute value.

**Comment by Josh68** [comment]
Thanks, Lenny. Hmmm, though I certainly could be missing something, it
looks to me like you incorporated my changes almost verbatim, so I'm not
sure I follow where we differed. Anyway, I bower-installed the latest and
it's working in my project, so all's good.

Cheers,

Josh
